=== ilyaonishenko/epam-hw/xml/src/main/resources/library.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://helloworld.org"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:normalizedString" minOccurs="1"/>
                            <xs:element name="author" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-z\s]*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pages" type="xs:int" minOccurs="1"/>
                            <xs:element name="publisher" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="AST"/>
                                        <xs:enumeration value="Piter"/>
                                        <xs:enumeration value="EKSMO"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="year">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:maxInclusive value="2016"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="onHang">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="true"/>
                                        <xs:enumeration value="false"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="size" type="xs:int" use="optional"/>
                        <xs:attribute name="id" type="xs:ID" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ilyaonishenko/epam-hw/xml/src/main/resources/Library.xml
<?xml version="1.0" encoding="utf-8"?>
<!--<library xmlns:xsi="http://helloworld.org"-->
         <!--xsi:schemaLocation="http://helloworld.org library.xsd">-->
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://helloworld.org"
    xsi:schemaLocation="http://helloworld.org library.xsd">
    <book>
        <name>1984</name>
        <author>George Orwell</author>
        <pages>384</pages>
        <publisher>EKSMO</publisher>
        <year>2010</year>
        <onHang>true</onHang>
    </book>
    <book>
        <name>Brave New World</name>
        <author>Aldous Huxley</author>
        <pages>400</pages>
        <publisher>EKSMO</publisher>
        <year>2007</year>
        <onHang>false</onHang>
    </book>
    <book>
        <name>Lord of the Flies</name>
        <author>William Gerald Golding</author>
        <pages>259</pages>
        <publisher>AST</publisher>
        <year>2015</year>
        <onHang>true</onHang>
    </book>
    <book>
        <name>We</name>
        <author>Yevgeny Zamyatin</author>
        <pages>200</pages>
        <publisher>Piter</publisher>
        <year>2016</year>
        <onHang>true</onHang>
    </book>
</library>
